# https://taskfile.dev

version: '3'

env:
  CPPYGEN_COMPILE_FLAGS: -isystem/usr/local/opt/llvm/lib/clang/15.0.7/include -Wall -Wextra
  CPPYGEN_LIBCLANG_PATH: /usr/local/opt/llvm/lib/libclang.dylib
  CC: /usr/local/opt/llvm/bin/clang
  CXX: /usr/local/opt/llvm/bin/clang++

tasks:
  compile:
    cmds:
      - cmake . -B build
      - cmake --build build
    silent: true
