# https://taskfile.dev

version: '3'

env:
  CPPYGEN_COMPILE_FLAGS: -isystem/usr/local/opt/llvm/lib/clang/15.0.7/include
  CPPYGEN_LIBCLANG_PATH: /usr/local/opt/llvm/lib/libclang.dylib

tasks:
  test:
    cmds:
      - pytest -vv
    silent: true
