# https://taskfile.dev

version: '3'

env:
  CPPYGEN_COMPILE_FLAGS: -isystem/Library/Developer/CommandLineTools/usr/lib/swift/clang/include
  CPPYGEN_LIBCLANG_PATH: /Library/Developer/CommandLineTools/usr/lib/libclang.dylib

tasks:
  test:
    cmds:
      - pytest -vv
    silent: true
