name: Publish distributions to PyPI or TestPyPI

# TestPyPI upload is scheduled in each weekday.
# PyPI upload is only activated if the release is published.
on:
  schedule:
    - cron: '0 15 * * *'
  release:
    types:
      - published

jobs:
  build-n-publish:
    name: Build and publish Python distributions to PyPI or TestPyPI
    runs-on: ubuntu-latest

    # Not intended for forks.
    if: github.repository == 'gen740/cppygen'

    steps:
    - uses: actions/checkout@v3
    - name: Setup Python3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install Poetry
      uses: snok/install-poetry@v1

    - name: Build a tar ball
      run: |
        poetry build

    - name: Publish distribution to TestPyPI
      # The following upload action cannot be executed in the forked repository.
      if: (github.event_name == 'schedule') || (github.event_name == 'release')
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.test_pypi_password }}
        repository_url: https://test.pypi.org/legacy/

    - name: Publish distribution to PyPI
      # The following upload action cannot be executed in the forked repository.
      if: github.event_name == 'release'
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.pypi_password }}
